# Generated by Django 5.2.9 on 2025-12-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('conteudo', models.TextField()),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True)),
                ('publico', models.BooleanField(default=False)),
                ('compartilhado_com', models.ManyToManyField(blank=True, related_name='notebooks_compartilhados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notebook de Análise',
                'verbose_name_plural': 'Notebooks de Análise',
            },
        ),
        migrations.CreateModel(
            name='EntidadeAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pessoa', 'Pessoa'), ('organizacao', 'Organização'), ('local', 'Local'), ('evento', 'Evento'), ('outro', 'Outro')], max_length=30)),
                ('dados', models.TextField()),
                ('coordenada_x', models.FloatField(blank=True, null=True)),
                ('coordenada_y', models.FloatField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='i2_analysis_notebook.notebookanalise')),
            ],
            options={
                'verbose_name': 'Entidade de Análise',
                'verbose_name_plural': 'Entidades de Análise',
            },
        ),
        migrations.CreateModel(
            name='ConexaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conexao', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.FloatField(default=1.0)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='i2_analysis_notebook.entidadeanalise')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='i2_analysis_notebook.entidadeanalise')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='i2_analysis_notebook.notebookanalise')),
            ],
            options={
                'verbose_name': 'Conexão de Análise',
                'verbose_name_plural': 'Conexões de Análise',
                'unique_together': {('origem', 'destino', 'tipo_conexao')},
            },
        ),
    ]
