# Generated by Django 5.2.9 on 2025-12-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('template', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Relatório',
                'verbose_name_plural': 'Tipos de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('parametros', models.TextField(blank=True)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('docx', 'Word'), ('html', 'HTML'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('publico', models.BooleanField(default=False)),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('parametros', models.TextField(blank=True)),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('personalizada', 'Personalizada')], max_length=20)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('dia_mes', models.IntegerField(blank=True, null=True)),
                ('hora_execucao', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Agendamento de Relatório',
                'verbose_name_plural': 'Agendamentos de Relatórios',
            },
        ),
    ]
