# Generated by Django 5.2.9 on 2025-12-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('banco_dados', 'Banco de Dados'), ('api', 'API'), ('arquivo', 'Arquivo'), ('web_scraping', 'Web Scraping'), ('outro', 'Outro')], max_length=30)),
                ('url_conexao', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
            },
        ),
        migrations.CreateModel(
            name='Cruzamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('parametros', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('tempo_execucao_segundos', models.FloatField(blank=True, null=True)),
                ('executado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fontes', models.ManyToManyField(related_name='cruzamentos', to='cruzamento_de_dados.fontedados')),
            ],
            options={
                'verbose_name': 'Cruzamento de Dados',
                'verbose_name_plural': 'Cruzamentos de Dados',
            },
        ),
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_a', models.CharField(max_length=200)),
                ('entidade_b', models.CharField(max_length=200)),
                ('tipo_relacionamento', models.CharField(choices=[('familiar', 'Familiar'), ('financeiro', 'Financeiro'), ('profissional', 'Profissional'), ('social', 'Social'), ('criminal', 'Criminal'), ('outro', 'Outro')], max_length=20)),
                ('grau_confianca', models.IntegerField(default=1)),
                ('evidencias', models.TextField(blank=True)),
                ('data_descoberta', models.DateTimeField(auto_now_add=True)),
                ('cruzamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos', to='cruzamento_de_dados.cruzamento')),
            ],
            options={
                'verbose_name': 'Relacionamento',
                'verbose_name_plural': 'Relacionamentos',
            },
        ),
    ]
