# Generated by Django 5.2.9 on 2025-12-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('exclusao', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('exportacao', 'Exportação'), ('outro', 'Outro')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Inteiro'), ('float', 'Número Decimal'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', max_length=20)),
                ('editavel_roles', models.ManyToManyField(blank=True, help_text='Roles que podem editar esta configuração', related_name='configuracoes_editaveis', to='users.role')),
                ('visivel_roles', models.ManyToManyField(blank=True, help_text='Roles que podem visualizar esta configuração', related_name='configuracoes_visiveis', to='users.role')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('importante', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('lida_por', models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoCustomizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('roles_autorizadas', models.ManyToManyField(blank=True, related_name='permissoes_customizadas', to='users.role')),
            ],
            options={
                'verbose_name': 'Permissão Customizada',
                'verbose_name_plural': 'Permissões Customizadas',
            },
        ),
    ]
