# Generated by Django 5.2.9 on 2025-12-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadePolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('patrulha', 'Patrulha'), ('viatura', 'Viatura'), ('helicoptero', 'Helicóptero'), ('base', 'Base Policial')], max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('disponivel', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('contato_radio', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Unidade Policial',
                'verbose_name_plural': 'Unidades Policiais',
            },
        ),
        migrations.CreateModel(
            name='ChamadaSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_origem', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('endereco', models.TextField(blank=True)),
                ('descricao', models.TextField()),
                ('data_hora_chamada', models.DateTimeField(auto_now_add=True)),
                ('data_hora_atendimento', models.DateTimeField(blank=True, null=True)),
                ('data_hora_encerramento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_atendimento', 'Em Atendimento'), ('atendida', 'Atendida'), ('encerrada', 'Encerrada')], default='recebida', max_length=20)),
                ('duracao_segundos', models.IntegerField(blank=True, null=True)),
                ('prioridade', models.IntegerField(default=1)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_atendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamada SOS',
                'verbose_name_plural': 'Chamadas SOS',
            },
        ),
    ]
