# Generated by Django 5.2.9 on 2025-12-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_penal', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Crime',
                'verbose_name_plural': 'Tipos de Crimes',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registrado', 'Registrado'), ('investigando', 'Em Investigação'), ('resolvido', 'Resolvido'), ('arquivado', 'Arquivado')], default='registrado', max_length=20)),
                ('nivel_gravidade', models.IntegerField(default=1)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminalidade.tipocrime')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_envolvimento', models.CharField(choices=[('vitima', 'Vítima'), ('suspeito', 'Suspeito'), ('testemunha', 'Testemunha'), ('outro', 'Outro')], max_length=20)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('contato', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvidos', to='criminalidade.ocorrencia')),
            ],
            options={
                'verbose_name': 'Envolvido',
                'verbose_name_plural': 'Envolvidos',
            },
        ),
    ]
