# Generated by Django 5.2.9 on 2025-12-16 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteRSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fonte RSS',
                'verbose_name_plural': 'Fontes RSS',
            },
        ),
        migrations.CreateModel(
            name='NoticiaRSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('data_publicacao', models.DateTimeField()),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('conteudo', models.TextField(blank=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('relevancia', models.IntegerField(default=1)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='servico_rss.fonterss')),
            ],
            options={
                'verbose_name': 'Notícia RSS',
                'verbose_name_plural': 'Notícias RSS',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
