# Generated by Django 5.2.9 on 2025-12-05 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('passaporte', 'Passaporte'), ('cnh', 'CNH'), ('certidao', 'Certidão'), ('outro', 'Outro')], max_length=20)),
                ('nome_titular', models.CharField(max_length=200)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=100)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
