# Generated by Django 5.2.9 on 2025-12-05 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoSuspeita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('fonte', models.CharField(max_length=100)),
                ('nivel_confianca', models.IntegerField(default=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_suspeitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informação Suspeita',
                'verbose_name_plural': 'Informações Suspeitas',
            },
        ),
    ]
