# Generated by Django 5.2.9 on 2025-12-05 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('chassi', models.CharField(max_length=20, unique=True)),
                ('proprietario', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('roubo', 'Roubo/Furto'), ('apreendido', 'Apreendido')], default='ativo', max_length=20)),
                ('ultima_posicao_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_posicao_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
            },
        ),
        migrations.CreateModel(
            name='RegistroMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidade', models.IntegerField(blank=True, null=True)),
                ('direcao', models.CharField(blank=True, max_length=10)),
                ('data_registro', models.DateTimeField()),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_monitoramento', to='monitoramento_de_viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Registro de Monitoramento',
                'verbose_name_plural': 'Registros de Monitoramento',
            },
        ),
    ]
