# Generated by Django 5.2.9 on 2025-12-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrusionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_device', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intrusion Session',
                'verbose_name_plural': 'Intrusion Sessions',
            },
        ),
        migrations.CreateModel(
            name='IntrusionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='invasao.intrusionsession')),
            ],
            options={
                'verbose_name': 'Intrusion Log',
                'verbose_name_plural': 'Intrusion Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CapturedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='invasion_media/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('metadata', models.TextField(blank=True, help_text='JSON formatted metadata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_media', to='invasao.intrusionsession')),
            ],
            options={
                'verbose_name': 'Captured Media',
                'verbose_name_plural': 'Captured Media',
                'ordering': ['-timestamp'],
            },
        ),
    ]
